#ifndef XAV_DATABASE_ENGINE_GLOBAL_H
#define XAV_DATABASE_ENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XAV_DATABASE_ENGINE_LIBRARY)
#  define XAV_DATABASE_ENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define XAV_DATABASE_ENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XAV_DATABASE_ENGINE_GLOBAL_H
