#ifndef XAV_NETWORK_ENGINE_GLOBAL_H
#define XAV_NETWORK_ENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XAV_NETWORK_ENGINE_LIBRARY)
#  define XAV_NETWORK_ENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define XAV_NETWORK_ENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XAV_NETWORK_ENGINE_GLOBAL_H
